### ISSUE TITLE
Come up with project idea!

### ISSUE THREAD

**Issue by fmtabbara** [chingu-voyages/v39-bears-team-12#7]
- Netflix Dashboard Clone
- Messenger app
- Cinema booking app

**Comment by elroi99** [comment]
### Notion database clone 
For reference :  https://www.notion.so/help/guides/when-to-use-each-type-of-database-view

My concerns about this project
1. The database component seems pretty complex. 
2. This might just a front-end heavy project. 

### Trello Clone

**Comment by kaoumrf** [comment]
**Assets DApp**

Assets ( Real estate, paintings etc) management using Decentralized App by digitally representing the assets contracts and store on an ERC-721 token which will be stored on the Ethereum Blockchain for added safety through the immutable nature of blockchain.

The process of transferring ownership of any asset can be made more time-efficient and less prone to the problems which arise from paper based transactions such as that of double spending.

Inspired from: https://medium.com/@stakeey/exploring-erc-721-use-cases-for-the-stakeey-decentralized-application-42b70ccdde4b

**Comment by PDavor** [comment]
Test tracking app

MVP:
Users can write test cases for projects, create test runs, milestones... Tests have steps to follow, expected results, and status (passed, failed, etc..). 
For advanced we could add integration with Github so you can create bug reports in-app that automatically show in Github.

**Comment by nasrullahiolamide** [comment]
Delivery Application for a store

The User will be able to login and make order and keep record of transactions
